### ISSUE TITLE
Example missing a json file

### ISSUE THREAD

**Issue by leonidprinceton** [chen-pin/ebs#6]
When running "python example.py" it gives:

Traceback (most recent call last):
  File "example.py", line 133, in <module>
    nemati2020_vvc6()
  File "example.py", line 28, in nemati2020_vvc6
    ref_json_filename=config['json_files']['ref_json'],
KeyError: 'ref_json'

**Comment by steigersg** [comment]
The example.py script has been deprecated with the recent feature additions so I would recommend running the code in the main() function of ebs/cli_interface.py even if you don't want to use the command line functionality where you would just have to change 

`config = args.config`

to 

`config = "path/to/your/parameters.yml"`

and you will have to manually set the `parameter` and `subparameter` keywords also in the main() function of cli_interface.py

That does raise the question though for @chen-pin of what we want that example.py script to contain/if we should remove that

**Comment by chen-pin** [comment]
I suggest removing example.py since it's deprecated.
